#!/bin/bash

if [ "$#" == "0" ]; then
    echo "Usage: $0 sources${top}."
    exit 1
fi

source /root/bin/common

#syntax=-fsyntax-only
errors=-fmax-errors=1

for i
do 
    echo "g++ ${syntax} ${flags} ${errors} -c $i -o compile.o"
    g++ ${syntax} ${errors} ${flags} -c $i -o compile.o
done
