#!/bin/bash

if [ "$#" == "0" ]; then
    echo "Usage: $0 sources${top}."
    exit 1
fi

source /root/bin/common

syntax=-fsyntax-only

for i
do 
    echo "g++ ${flags} -c $i -o compile.o"
    g++ ${flags} ${syntax} -c $i -o compile.o
done
